In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup
import requests
from urllib.request import urlopen


import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_csv('../input/2012_qb_weeks1_8.csv')
df1=pd.read_csv('../input/2012_qb_weeks_9_16.csv')
df3 = pd.read_csv('../input/2012_qb_week17.csv')

In [3]:
raw_qb_2012 = pd.concat([df,df1], axis=0)
raw_qb_2012 = pd.concat([raw_qb_2012, df3], axis=0)html = urlopen(url)

raw_qb_2012.shape

(629, 19)

In [57]:
raw_qb_2012.head()

,Rk,Player,Pos,Week,Team,Opp,Comp,Att,Pct,Yds,Yds/Att,TD,Int,QB Rating,rush_att,rush_yds,rush_yd/att,rush_td,Fantasy Points
0,1,Matt Ryan,QB,1,ATL,KC,23,31,74,299,10,3,0,136,3,25,8,1,32.46
1,2,Robert Griffin III,QB,1,WAS,NO,19,26,73,320,12,2,0,140,9,42,5,0,25.00
2,3,Tony Romo,QB,1,DAL,NYG,22,29,76,307,11,3,1,130,5,12,2,0,23.48
3,4,Aaron Rodgers,QB,1,GB,SF,30,44,68,303,7,2,1,93,5,27,5,0,22.82
4,5,Drew Brees,QB,1,NO,WAS,24,52,46,339,7,3,2,71,0,0,0,0,21.56

In [84]:
url=('https://www.pro-football-reference.com/years/2012/week_1.htm')
html = urlopen(url)
bsobj= BeautifulSoup(html, 'lxml')

In [90]:
bsobj.tbody.td{'colspan'}

SyntaxError: invalid syntax (<ipython-input-90-73485dd85620>, line 1)

In [4]:
raw_qb_2012 = raw_qb_2012.rename(columns={'Att.1':'rush_att',
                       'Yds.1':'rush_yds',
                       'Yds/Att.1':'rush_yd/att',
                       'TD.1':'rush_td'})

In [ ]:
weekly_stats = raw_qb_2012.groupby(['Player', 'Week']).sum()

In [66]:
team_stats = raw_qb_2012.groupby(['Player','Team', 'Week','Opp']).sum()

In [67]:
team_stats.head()

                              Rk  Comp  Att  Pct  Yds  Yds/Att  TD  Int  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF     4    30   44   68  303        7   2    1
                   2    CHI   65    22   32   69  219        7   1    1
                   3    SEA   97    26   39   67  223        6   0    0
                   4    NO   117    31   41   76  319        8   4    1
                   5    IND  155    20   32   63  235        7   3    1

                             QB Rating  rush_att  rush_yds  rush_yd/att  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF          93         5        27            5
                   2    CHI         85         3        -6           -2
                   3    SEA         81         2        17            9
                   4    NO         120         5        13            3
                   5    IND        103         5        57           11

                             rush_td  Fantasy Points
Player        Team Week Opp
Aaron Rodgers GB   1    SF         0           22.82
                   2    CHI        0           10.16
                   3    SEA        0           10.62
                   4    NO         0           28.06
                   5    IND        0           25.10

In [58]:
weekly_stats.head()

                     Rk  Comp  Att  Pct  Yds  Yds/Att  TD  Int  QB Rating  \
Player        Week
Aaron Rodgers 1       4    30   44   68  303        7   2    1         93
              2      65    22   32   69  219        7   1    1         85
              3      97    26   39   67  223        6   0    0         81
              4     117    31   41   76  319        8   4    1        120
              5     155    20   32   63  235        7   3    1        103

                    rush_att  rush_yds  rush_yd/att  rush_td  Fantasy Points
Player        Week
Aaron Rodgers 1            5        27            5        0           22.82
              2            3        -6           -2        0           10.16
              3            2        17            9        0           10.62
              4            5        13            3        0           28.06
              5            5        57           11        0           25.10

In [6]:
y=weekly_stats['Fantasy Points']

In [7]:
def create_recent_dataframe(df):
    columns = []
    for col in df.columns:
        columns.append('avg_{}'.format(col.lower()))
    new_df = pd.DataFrame(columns=columns, index =df.index)
    return new_df

In [68]:
qb_2012_recent_df = create_recent_dataframe(team_stats)

In [69]:
qb_2012_recent_df.head()

                            avg_rk avg_comp avg_att avg_pct avg_yds  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF     NaN      NaN     NaN     NaN     NaN
                   2    CHI    NaN      NaN     NaN     NaN     NaN
                   3    SEA    NaN      NaN     NaN     NaN     NaN
                   4    NO     NaN      NaN     NaN     NaN     NaN
                   5    IND    NaN      NaN     NaN     NaN     NaN

                            avg_yds/att avg_td avg_int avg_qb rating  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF          NaN    NaN     NaN           NaN
                   2    CHI         NaN    NaN     NaN           NaN
                   3    SEA         NaN    NaN     NaN           NaN
                   4    NO          NaN    NaN     NaN           NaN
                   5    IND         NaN    NaN     NaN           NaN

                            avg_rush_att avg_rush_yds avg_rush_yd/att  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF           NaN          NaN             NaN
                   2    CHI          NaN          NaN             NaN
                   3    SEA          NaN          NaN             NaN
                   4    NO           NaN          NaN             NaN
                   5    IND          NaN          NaN             NaN

                            avg_rush_td avg_fantasy points
Player        Team Week Opp
Aaron Rodgers GB   1    SF          NaN                NaN
                   2    CHI         NaN                NaN
                   3    SEA         NaN                NaN
                   4    NO          NaN                NaN
                   5    IND         NaN                NaN

In [70]:
for col in weekly_stats:
    lst=[]
    for player in weekly_stats.index.levels[0]:
        total =[]
        for week in weekly_stats.loc[player].index:
            total.append(weekly_stats.loc[player].loc[week][col])
            lst.append(np.mean(total))
    qb_2012_recent_df['avg_{}'.format(col.lower())] = lst

In [71]:
qb_2012_recent_df.shape

(629, 14)

In [12]:
qb_2012_recent['fantasy_points']=y

In [76]:
qb_2012_recent_df

                                 avg_rk   avg_comp    avg_att     avg_pct  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF     4.000000  30.000000  44.000000   68.000000
                   2    CHI   34.500000  26.000000  38.000000   68.500000
                   3    SEA   55.333333  26.000000  38.333333   68.000000
                   4    NO    70.750000  27.250000  39.000000   70.000000
                   5    IND   87.600000  25.800000  37.600000   68.600000
                   6    HOU  104.500000  25.500000  37.500000   68.000000
                   7    LAR  121.571429  26.142857  37.428571   69.857143
                   8    JAX  139.875000  25.625000  37.125000   69.000000
                   9    ARI  124.555556  24.333333  36.333333   66.555556
                   11   DET  120.300000  23.800000  35.400000   66.900000
                   12   NYG  120.909091  22.909091  34.454545   65.909091
                   13   MIN  124.083333  23.250000  34.500000   66.833333
                   14   DET  129.384615  22.538462  33.692308   66.153846
                   15   CHI  136.214286  22.571429  33.857143   66.000000
                   16   TEN  144.533333  22.866667  34.133333   66.333333
                   17   MIN  135.625000  23.187500  34.500000   66.562500
Alex Smith    SF   1    GB    12.000000  20.000000  26.000000   77.000000
                   2    DET   33.500000  20.000000  28.500000   71.000000
                   3    MIN   54.333333  21.333333  30.666667   70.333333
                   4    NYJ   75.750000  19.000000  28.250000   67.000000
                   5    BUF   91.000000  18.800000  27.400000   68.600000
                   6    NYG  112.000000  18.833333  27.833333   67.666667
                   7    SEA  130.571429  18.142857  27.142857   66.714286
                   8    ARI  146.500000  18.125000  26.125000   70.250000
                   10   LAR  136.222222  16.888889  24.111111   72.222222
                   11   CHI  132.900000  15.200000  21.700000   65.000000
                   12   NO   133.727273  13.818182  19.727273   59.090909
                   13   LAR  137.333333  12.666667  18.083333   54.166667
                   14   MIA  143.384615  11.692308  16.692308   50.000000
                   15   NE   151.500000  10.857143  15.500000   46.428571
...                                 ...        ...        ...         ...
Tom Brady     NE   11   IND  123.300000  25.600000  39.300000   65.800000
                   12   NYJ  121.818182  24.909091  38.181818   65.909091
                   13   MIA  125.583333  24.833333  38.333333   65.416667
                   14   HOU  129.846154  24.538462  38.076923   65.000000
                   15   SF   136.714286  25.357143  40.000000   64.285714
                   16   JAX  145.866667  25.266667  40.066667   63.933333
                   17   MIA  137.250000  25.062500  39.812500   63.750000
Tony Romo     DAL  1    NYG    3.000000  22.000000  29.000000   76.000000
                   2    SEA   33.000000  22.500000  34.500000   67.000000
                   3    TB    57.000000  23.333333  36.000000   66.000000
                   4    CHI   78.250000  25.250000  37.750000   67.500000
                   6    BAL  103.000000  25.200000  37.400000   67.800000
                   7    CAR  124.833333  25.000000  36.833333   68.333333
                   8    NYG  144.142857  26.571429  40.428571   66.857143
                   9    ATL  127.500000  26.375000  39.750000   67.375000
                   10   PHI  118.666667  25.555556  38.222222   68.000000
                   11   CLE  115.100000  26.500000  39.400000   68.200000
                   12   WAS  114.545455  27.454545  41.454545   67.454545
                   13   PHI  117.250000  27.000000  40.250000   68.666667
                   14   CIN  123.384615  26.846154  40.461538   67.846154
                   15   PIT  131.000000  27.071429  40.571429   68.071429
                   16   NO   139.733333  27.000000  40.733333   67.600000
                   17   WAS  132.187500  26.562500  40.500000   66.750000
Trent Edwards PHI  17   NYG   34.000000   2.000000   2.000000  100.000000
Tyrod Taylor  BAL  1    CIN   33.000000   2.000000   3.000000   67.000000
                   4    CLE   90.000000   1.000000   1.500000   33.500000
                   5    KC   121.000000   0.666667   1.000000   22.333333
                   9    CLE   98.000000   0.500000   0.750000   16.750000
                   10   OAK   91.800000   0.400000   0.800000   13.400000
                   17   CIN   78.500000   2.833333   4.833333   21.166667

                                avg_yds  avg_yds/att    avg_td   avg_int  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF   303.000000     7.000000  2.000000  1.000000
                   2    CHI  261.000000     7.000000  1.500000  1.000000
                   3    SEA  248.333333     6.666667  1.000000  0.666667
                   4    NO   266.000000     7.000000  1.750000  0.750000
                   5    IND  259.800000     7.000000  2.000000  0.800000
                   6    HOU  272.833333     7.333333  2.666667  0.666667
                   7    LAR  282.714286     7.571429  2.714286  0.571429
                   8    JAX  270.625000     7.250000  2.625000  0.500000
                   9    ARI  264.777778     7.222222  2.777778  0.555556
                   11   DET  261.900000     7.400000  2.700000  0.600000
                   12   NYG  258.000000     7.545455  2.545455  0.636364
                   13   MIN  260.333333     7.583333  2.416667  0.666667
                   14   DET  253.615385     7.538462  2.230769  0.615385
                   15   CHI  256.285714     7.571429  2.285714  0.571429
                   16   TEN  262.000000     7.666667  2.333333  0.533333
                   17   MIN  268.437500     7.750000  2.437500  0.500000
Alex Smith    SF   1    GB   211.000000     8.000000  2.000000  0.000000
                   2    DET  218.500000     7.500000  2.000000  0.000000
                   3    MIN  213.666667     7.000000  1.666667  0.333333
                   4    NYJ  196.000000     7.000000  1.250000  0.250000
                   5    BUF  217.400000     8.200000  1.600000  0.200000
                   6    NYG  214.500000     8.000000  1.333333  0.666667
                   7    SEA  203.857143     7.714286  1.285714  0.714286
                   8    ARI  207.375000     8.250000  1.500000  0.625000
                   10   LAR  192.333333     8.333333  1.444444  0.555556
                   11   CHI  173.100000     7.500000  1.300000  0.500000
                   12   NO   157.363636     6.818182  1.181818  0.454545
                   13   LAR  144.250000     6.250000  1.083333  0.416667
                   14   MIA  133.153846     5.769231  1.000000  0.384615
                   15   NE   123.642857     5.357143  0.928571  0.357143
...                                 ...          ...       ...       ...
Tom Brady     NE   11   IND  297.600000     7.700000  2.100000  0.300000
                   12   NYJ  299.909091     8.090909  2.181818  0.272727
                   13   MIA  294.750000     7.916667  2.083333  0.333333
                   14   HOU  294.846154     8.000000  2.230769  0.307692
                   15   SF   305.428571     7.928571  2.142857  0.428571
                   16   JAX  302.866667     7.866667  2.133333  0.533333
                   17   MIA  301.687500     7.875000  2.125000  0.500000
Tony Romo     DAL  1    NYG  307.000000    11.000000  3.000000  1.000000
                   2    SEA  279.000000     8.500000  2.000000  1.000000
                   3    TB   280.333333     8.000000  1.333333  1.000000
                   4    CHI  287.000000     7.750000  1.250000  2.000000
                   6    BAL  281.800000     7.600000  1.400000  1.800000
                   7    CAR  272.666667     7.500000  1.333333  1.500000
                   8    NYG  296.142857     7.428571  1.285714  1.857143
                   9    ATL  299.250000     7.625000  1.250000  1.625000
                   10   PHI  289.222222     7.666667  1.333333  1.444444
                   11   CLE  291.600000     7.500000  1.300000  1.300000
                   12   WAS  305.181818     7.454545  1.454545  1.363636
                   13   PHI  305.000000     7.750000  1.583333  1.250000
                   14   CIN  302.153846     7.615385  1.538462  1.230769
                   15   PIT  304.928571     7.642857  1.571429  1.142857
                   16   NO   312.333333     7.800000  1.733333  1.066667
                   17   WAS  306.437500     7.687500  1.750000  1.187500
Trent Edwards PHI  17   NYG   14.000000     7.000000  0.000000  0.000000
Tyrod Taylor  BAL  1    CIN   30.000000    10.000000  0.000000  0.000000
                   4    CLE   15.000000     5.000000  0.000000  0.000000
                   5    KC    10.000000     3.333333  0.000000  0.000000
                   9    CLE    7.500000     2.500000  0.000000  0.000000
                   10   OAK    6.000000     2.000000  0.000000  0.000000
                   17   CIN   29.833333     2.666667  0.000000  0.166667

                             avg_qb rating  avg_rush_att  avg_rush_yds  \
Player        Team Week Opp
Aaron Rodgers GB   1    SF       93.000000      5.000000     27.000000
                   2    CHI      89.000000      4.000000     10.500000
                   3    SEA      86.333333      3.333333     12.666667
                   4    NO       94.750000      3.750000     12.750000
                   5    IND      96.400000      4.000000     21.600000
                   6    HOU     102.666667      3.666667     20.833333
                   7    LAR     106.857143      3.428571     17.857143
                   8    JAX     105.500000      3.375000     16.125000
                   9    ARI     104.555556      3.888889     18.000000
                   11   DET     104.700000      3.600000     16.500000
                   12   NYG     102.636364      3.545455     17.000000
                   13   MIN     102.250000      3.583333     16.833333
                   14   DET     100.615385      3.538462     18.000000
                   15   CHI     101.785714      3.571429     17.714286
                   16   TEN     103.333333      3.600000     17.266667
                   17   MIN     105.125000      3.375000     16.187500
Alex Smith    SF   1    GB      126.000000      5.000000     13.000000
                   2    DET     117.000000      4.500000     10.000000
                   3    MIN     105.000000      4.333333     15.333333
                   4    NYJ      98.250000      4.000000     14.500000
                   5    BUF     109.800000      3.800000     21.400000
                   6    NYG      98.666667      3.500000     18.666667
                   7    SEA      95.285714      3.714286     17.571429
                   8    ARI     103.000000      3.375000     16.125000
                   10   LAR     107.555556      3.222222     14.888889
                   11   CHI      96.800000      2.900000     13.400000
                   12   NO       88.000000      2.636364     12.181818
                   13   LAR      80.666667      2.416667     11.166667
                   14   MIA      74.461538      2.230769     10.307692
                   15   NE       69.142857      2.071429      9.571429
...                                    ...           ...           ...
Tom Brady     NE   11   IND     105.100000      1.200000      1.100000
                   12   NYJ     108.727273      1.363636      1.454545
                   13   MIA     105.916667      1.583333      1.250000
                   14   HOU     107.384615      1.538462      1.615385
                   15   SF      104.642857      1.642857      2.285714
                   16   JAX     102.600000      1.533333      2.133333
                   17   MIA     102.687500      1.437500      2.000000
Tony Romo     DAL  1    NYG     130.000000      5.000000     12.000000
                   2    SEA     102.000000      3.500000      5.500000
                   3    TB       93.000000      3.666667      4.000000
                   4    CHI      84.750000      3.000000      3.000000
                   6    BAL      87.200000      2.400000      2.400000
                   7    CAR      89.166667      2.500000      3.833333
                   8    NYG      84.714286      2.428571      3.285714
                   9    ATL      87.750000      2.125000      2.875000
                   10   PHI      91.555556      2.000000      2.444444
                   11   CLE      91.700000      2.000000      3.200000
                   12   WAS      91.000000      2.090909      3.545455
                   13   PHI      95.916667      2.166667      4.416667
                   14   CIN      94.307692      2.000000      4.076923
                   15   PIT      95.500000      2.142857      3.500000
                   16   NO       97.400000      2.000000      3.266667
                   17   WAS      94.812500      1.875000      3.062500
Trent Edwards PHI  17   NYG      96.000000      0.000000      0.000000
Tyrod Taylor  BAL  1    CIN      99.000000      1.000000      7.000000
                   4    CLE      49.500000      0.500000      3.500000
                   5    KC       33.000000      0.333333      2.333333
                   9    CLE      24.750000      0.500000      2.750000
                   10   OAK      27.800000      0.400000      2.200000
                   17   CIN      33.166667      1.833333     12.666667

                             avg_rush_yd/att  avg_rush_td  avg_fantasy points
Player        Team Week Opp
Aaron Rodgers GB   1    SF          5.000000     0.000000           22.820000
                   2    CHI         1.500000     0.000000           16.490000
                   3    SEA         4.000000     0.000000           14.533333
                   4    NO          3.750000     0.000000           17.915000
                   5    IND         5.200000     0.000000           19.352000
                   6    HOU         5.833333     0.000000           22.663333
                   7    LAR         5.000000     0.000000           23.094286
                   8    JAX         4.500000     0.000000           21.937500
                   9    ARI         4.444444     0.000000           22.391111
                   11   DET         4.300000     0.000000           21.726000
                   12   NYG         4.545455     0.000000           20.747273
                   13   MIN         4.500000     0.000000           20.263333
                   14   DET         5.000000     0.076923           19.790769
                   15   CHI         4.928571     0.071429           20.230000
                   16   TEN         4.800000     0.133333           21.066667
                   17   MIN         4.500000     0.125000           21.537500
Alex Smith    SF   1    GB          3.000000     0.000000           17.740000
                   2    DET         2.500000     0.000000           17.740000
                   3    MIN         4.000000     0.000000           15.413333
                   4    NYJ         4.000000     0.000000           13.290000
                   5    BUF         6.400000     0.000000           16.436000
                   6    NYG         5.833333     0.000000           14.113333
                   7    SEA         5.285714     0.000000           13.340000
                   8    ARI         5.375000     0.000000           14.407500
                   10   LAR         5.111111     0.000000           13.626667
                   11   CHI         4.600000     0.000000           12.264000
                   12   NO          4.181818     0.000000           11.149091
                   13   LAR         3.833333     0.000000           10.220000
                   14   MIA         3.538462     0.000000            9.433846
                   15   NE          3.285714     0.000000            8.760000
...                                      ...          ...                 ...
Tom Brady     NE   11   IND         0.900000     0.200000           21.014000
                   12   NYJ         1.000000     0.272727           21.960000
                   13   MIA         0.916667     0.250000           21.081667
                   14   HOU         1.307692     0.230769           21.647692
                   15   SF          1.500000     0.285714           21.874286
                   16   JAX         1.400000     0.266667           21.394667
                   17   MIA         1.312500     0.250000           21.267500
Tony Romo     DAL  1    NYG         2.000000     0.000000           23.480000
                   2    SEA         0.500000     0.000000           17.710000
                   3    TB          0.333333     0.000000           13.580000
                   4    CHI         0.250000     0.000000           11.755000
                   6    BAL         0.200000     0.000000           12.692000
                   7    CAR         0.833333     0.000000           12.940000
                   8    NYG         0.714286     0.142857           13.874286
                   9    ATL         0.625000     0.125000           14.245000
                   10   PHI         0.444444     0.111111           14.468889
                   11   CLE         0.900000     0.100000           14.574000
                   12   WAS         1.000000     0.090909           15.825455
                   13   PHI         1.333333     0.083333           16.633333
                   14   CIN         1.230769     0.076923           16.332308
                   15   PIT         1.071429     0.071429           16.682857
                   16   NO          1.000000     0.066667           17.746667
                   17   WAS         0.937500     0.062500           17.432500
Trent Edwards PHI  17   NYG         0.000000     0.000000            0.560000
Tyrod Taylor  BAL  1    CIN         7.000000     0.000000            1.900000
                   4    CLE         3.500000     0.000000            0.950000
                   5    KC          2.333333     0.000000            0.633333
                   9    CLE         2.750000     0.000000            0.575000
                   10   OAK         2.200000     0.000000            0.460000
                   17   CIN         3.000000     0.166667            3.126667

[629 rows x 14 columns]

In [75]:
raw_qb_2012[raw_qb_2012.Player=='Aaron Rodgers']

,Rk,Player,Pos,Week,Team,Opp,Comp,Att,Pct,Yds,Yds/Att,TD,Int,QB Rating,rush_att,rush_yds,rush_yd/att,rush_td,Fantasy Points
3,4,Aaron Rodgers,QB,1,GB,SF,30,44,68,303,7,2,1,93,5,27,5,0,22.82
64,65,Aaron Rodgers,QB,2,GB,CHI,22,32,69,219,7,1,1,85,3,-6,-2,0,10.16
96,97,Aaron Rodgers,QB,3,GB,SEA,26,39,67,223,6,0,0,81,2,17,9,0,10.62
116,117,Aaron Rodgers,QB,4,GB,NO,31,41,76,319,8,4,1,120,5,13,3,0,28.06
154,155,Aaron Rodgers,QB,5,GB,IND,20,32,63,235,7,3,1,103,5,57,11,0,25.10
188,189,Aaron Rodgers,QB,6,GB,HOU,24,37,65,338,9,6,0,134,2,17,9,0,39.22
223,224,Aaron Rodgers,QB,7,GB,LAR,30,37,81,342,9,3,0,132,2,0,0,0,25.68
267,268,Aaron Rodgers,QB,8,GB,JAX,22,35,63,186,5,2,0,96,3,4,1,0,13.84
1,2,Aaron Rodgers,QB,9,GB,ARI,14,30,47,218,7,4,1,97,8,33,4,0,26.02
81,82,Aaron Rodgers,QB,11,GB,DET,19,27,70,236,9,2,1,106,1,3,3,0,15.74
126,127,Aaron Rodgers,QB,12,GB,NYG,14,25,56,219,9,1,1,82,3,22,7,0,10.96
158,159,Aaron Rodgers,QB,13,GB,MIN,27,35,77,286,8,1,1,98,4,15,4,0,14.94
192,193,Aaron Rodgers,QB,14,GB,DET,14,24,58,173,7,0,0,81,3,32,11,1,14.12
224,225,Aaron Rodgers,QB,15,GB,CHI,23,36,64,291,8,3,0,117,4,14,4,0,25.94
260,261,Aaron Rodgers,QB,16,GB,TEN,27,38,71,342,9,3,0,125,4,11,3,1,32.78
1,2,Aaron Rodgers,QB,17,GB,MIN,28,40,70,365,9,4,0,132,0,0,0,0,28.60

In [16]:
qb_2012_recent.drop('avg_rk', axis=1, inplace=True)

In [47]:
count=0
for idx,row in enumerate(qb_2012_recent.index):
    if 1 in row:
        print(qb_2012_recent.values[idx])

[  30.     44.     68.    303.      7.      2.      1.     93.      5.
   27.      5.      0.     22.82   22.82]
[  20.     26.     77.    211.      8.      2.      0.    126.      5.
   13.      3.      0.     17.74   17.74]
[  23.     45.     51.    309.      7.      1.      3.     53.      2.
    9.      5.      0.      9.26    9.26]
[  22.     37.     60.    221.      6.      0.      1.     65.      3.
   11.      4.      0.      5.94    5.94]
[  22.    40.    55.   245.     6.     2.     1.    80.     2.     4.     2.
    0.    16.2   16.2]
[  23.   39.   59.  260.    7.    2.    0.   96.    5.    6.    1.    0.
   19.   19.]
[  12.     35.     34.    118.      3.      0.      4.      5.      2.
   25.     13.      0.     -0.78   -0.78]
[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[  23.     33.     70.    303.      9.      1.      2.     83.      5.
    4.      1.      0.     12.52   12.52]
[  32.     46.     70.    297.      7.      1.      0.     94.      0.
    0.      0.      0.     17.88   17.88]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  20.    27.    74.   270.    10.     0.     0.   105.     1.     1.     1.
    0.     8.9    8.9]
[  0.    0.    0.    0.    0.    0.    0.    0.    1.   17.   17.    0.
   1.7   1.7]
[  24.     52.     46.    339.      7.      3.      2.     71.      0.
    0.      0.      0.     21.56   21.56]
[  21.     32.     66.    213.      7.      1.      0.     95.      0.
    0.      0.      0.     12.52   12.52]
[  23.     32.     72.    229.      7.      1.      1.     89.      2.
   11.      6.      0.     10.26   10.26]
[  21.     35.     60.    333.     10.      2.      1.     99.      4.
   -4.     -1.      0.     18.92   18.92]
[  21.     29.     72.    299.     10.      2.      0.    128.      2.
   -1.     -1.      0.     19.86   19.86]
[  14.     28.     50.    149.      5.      0.      1.     51.      1.
    2.      2.      0.      4.16    4.16]
[  16.     24.     67.    138.      6.      1.      0.     95.      7.
   13.      2.      0.     10.82   10.82]
[   6.      8.     75.     66.      8.      1.      0.    139.      1.
   -1.     -1.      0.      6.54    6.54]
[  19.     27.     70.    266.     10.      3.      1.    123.      0.
    0.      0.      0.     20.64   20.64]
[  21.     33.     64.    258.      8.      1.      2.     73.      4.
   20.      5.      1.     16.32   16.32]
[  6.    11.    55.    43.     4.     0.     0.    64.     0.     0.     0.
   0.     1.72   1.72]
[  23.     31.     74.    299.     10.      3.      0.    136.      3.
   25.      8.      1.     32.46   32.46]
[  20.     31.     65.    266.      9.      1.      0.    102.      4.
   -2.     -1.      0.     14.44   14.44]
[  32.    48.    67.   355.     7.     1.     3.    69.     0.     0.     0.
    0.    12.5   12.5]
[  29.     56.     52.    317.      6.      2.      4.     51.      7.
   32.      5.      0.     15.88   15.88]
[  19.     26.     73.    253.     10.      2.      0.    129.      4.
    3.      1.      0.     20.42   20.42]
[  24.     33.     73.    231.      7.      1.      0.    102.      1.
   -2.     -2.      0.     13.04   13.04]
[  19.   26.   73.  320.   12.    2.    0.  140.    9.   42.    5.    0.
   25.   25.]
[  18.     34.     53.    153.      5.      1.      1.     63.      8.
   20.      3.      0.      8.12    8.12]
[  18.    32.    56.   195.     6.     3.     3.    67.     2.     8.     4.
    0.    14.6   14.6]
[  20.     36.     56.    219.      6.      0.      3.     39.      3.
   -4.     -1.      0.      2.36    2.36]
[  17.     25.     68.    198.      8.      1.      0.    105.      2.
    2.      1.      0.     12.12   12.12]
[  0.    0.    0.    0.    0.    0.    0.    0.    5.   11.    2.    0.
   1.1   1.1]
[  23.     31.     74.    236.      8.      2.      0.    117.      2.
    1.      1.      0.     17.54   17.54]
[  22.     29.     76.    307.     11.      3.      1.    130.      5.
   12.      2.      0.     23.48   23.48]
[  2.    3.   67.   30.   10.    0.    0.   99.    1.    7.    7.    0.
   1.9   1.9]

In [14]:
def create_dataset(dataset, look_back=1):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back), 0]
        dataX.append(a)
        dataY.append(dataset[i + look_back, 0])
    return np.array(dataX), np.array(dataY)

In [15]:
create_dataset(qb_2012_recent.values, look_back=1)

(array([[   4.        ],
        [  34.5       ],
        [  55.33333333],
        [  70.75      ],
        [  87.6       ],
        [ 104.5       ],
        [ 121.57142857],
        [ 139.875     ],
        [ 124.55555556],
        [ 120.3       ],
        [ 120.90909091],
        [ 124.08333333],
        [ 129.38461538],
        [ 136.21428571],
        [ 144.53333333],
        [ 135.625     ],
        [  12.        ],
        [  33.5       ],
        [  54.33333333],
        [  75.75      ],
        [  91.        ],
        [ 112.        ],
        [ 130.57142857],
        [ 146.5       ],
        [ 136.22222222],
        [ 132.9       ],
        [ 133.72727273],
        [ 137.33333333],
        [ 143.38461538],
        [ 151.5       ],
        [ 161.33333333],
        [ 153.5625    ],
        [  26.        ],
        [  37.5       ],
        [  52.33333333],
        [  77.5       ],
        [ 104.8       ],
        [ 125.5       ],
        [ 144.85714286],
        [ 127.125     ],
        [ 117.55555556],
        [ 114.4       ],
        [ 115.18181818],
        [ 117.66666667],
        [ 124.30769231],
        [ 132.07142857],
        [ 141.66666667],
        [ 133.6875    ],
        [  30.        ],
        [  37.        ],
        [  51.        ],
        [  69.        ],
        [  88.6       ],
        [ 106.83333333],
        [ 126.57142857],
        [ 112.25      ],
        [ 103.66666667],
        [ 100.8       ],
        [ 101.81818182],
        [ 106.66666667],
        [ 113.92307692],
        [ 122.71428571],
        [ 133.73333333],
        [ 127.        ],
        [  15.        ],
        [  33.        ],
        [  47.        ],
        [  76.25      ],
        [ 101.        ],
        [ 123.83333333],
        [ 143.14285714],
        [ 127.875     ],
        [ 119.44444444],
        [ 125.7       ],
        [ 135.27272727],
        [ 147.66666667],
        [ 137.15384615],
        [   9.        ],
        [  39.5       ],
        [  58.        ],
        [  77.        ],
        [  99.        ],
        [ 123.        ],
        [ 143.        ],
        [ 127.        ],
        [ 119.        ],
        [ 117.6       ],
        [ 182.        ],
        [ 198.5       ],
        [ 228.        ],
        [ 194.75      ],
        [ 183.        ],
        [ 178.16666667],
        [ 182.57142857],
        [ 190.75      ],
        [ 202.        ],
        [ 185.        ],
        [  39.        ],
        [  43.        ],
        [  61.66666667],
        [  80.25      ],
        [  96.8       ],
        [ 114.5       ],
        [ 130.71428571],
        [ 149.375     ],
        [ 135.66666667],
        [ 130.6       ],
        [ 130.63636364],
        [ 132.91666667],
        [ 138.23076923],
        [ 145.5       ],
        [ 155.13333333],
        [ 294.        ],
        [ 158.        ],
        [ 150.        ],
        [ 218.        ],
        [ 232.        ],
        [ 249.        ],
        [ 207.4       ],
        [  38.        ],
        [  34.5       ],
        [  60.        ],
        [  72.        ],
        [  21.        ],
        [  31.5       ],
        [  53.66666667],
        [  69.        ],
        [  90.2       ],
        [ 113.83333333],
        [ 136.14285714],
        [ 119.625     ],
        [ 111.88888889],
        [ 108.7       ],
        [ 108.45454545],
        [ 111.41666667],
        [ 116.61538462],
        [ 124.85714286],
        [ 134.4       ],
        [ 127.4375    ],
        [  11.        ],
        [  33.5       ],
        [  51.33333333],
        [  73.25      ],
        [  99.4       ],
        [ 120.5       ],
        [ 141.42857143],
        [ 123.875     ],
        [ 114.44444444],
        [ 111.1       ],
        [ 113.09090909],
        [ 116.        ],
        [ 121.84615385],
        [ 130.57142857],
        [ 141.53333333],
        [  74.        ],
        [ 160.5       ],
        [ 125.66666667],
        [ 112.5       ],
        [ 113.6       ],
        [ 122.        ],
        [ 134.71428571],
        [ 148.        ],
        [ 162.33333333],
        [ 147.6       ],
        [ 137.        ],
        [ 151.5       ],
        [  37.        ],
        [  55.        ],
        [  73.66666667],
        [  92.5       ],
        [ 111.        ],
        [ 134.33333333],
        [ 155.85714286],
        [ 140.125     ],
        [ 132.22222222],
        [ 128.8       ],
        [ 129.90909091],
        [ 133.75      ],
        [ 140.15384615],
        [ 148.35714286],
        [ 158.26666667],
        [ 150.875     ],
        [  27.        ],
        [  42.        ],
        [  54.        ],
        [  76.25      ],
        [  93.4       ],
        [ 111.        ],
        [ 130.57142857],
        [ 147.875     ],
        [ 134.55555556],
        [ 125.3       ],
        [ 125.90909091],
        [ 129.66666667],
        [ 136.07692308],
        [ 143.42857143],
        [ 152.4       ],
        [ 143.25      ],
        [  35.        ],
        [  85.        ],
        [ 114.66666667],
        [ 140.        ],
        [ 162.4       ],
        [ 142.66666667],
        [ 133.57142857],
        [ 131.125     ],
        [ 134.44444444],
        [ 139.6       ],
        [ 147.27272727],
        [ 157.66666667],
        [ 146.07692308],
        [ 139.        ],
        [ 178.5       ],
        [ 214.        ],
        [ 251.        ],
        [ 110.        ],
        [  73.        ],
        [ 108.        ],
        [  71.5       ],
        [   5.        ],
        [  27.5       ],
        [  46.66666667],
        [  64.        ],
        [  82.        ],
        [ 105.5       ],
        [ 128.28571429],
        [ 114.        ],
        [ 105.44444444],
        [ 102.7       ],
        [ 103.81818182],
        [ 109.66666667],
        [ 116.23076923],
        [ 123.78571429],
        [ 133.06666667],
        [ 124.8125    ],
        [  20.        ],
        [  30.5       ],
        [  50.66666667],
        [  69.75      ],
        [  87.2       ],
        [ 107.33333333],
        [ 125.57142857],
        [ 144.625     ],
        [ 131.55555556],
        [ 124.5       ],
        [ 123.27272727],
        [ 126.08333333],
        [ 130.46153846],
        [ 139.        ],
        [ 148.53333333],
        [ 139.4375    ],
        [ 151.        ],
        [ 185.        ],
        [ 169.33333333],
        [ 201.        ],
        [ 173.        ],
        [ 231.        ],
        [  25.        ],
        [  44.5       ],
        [  56.33333333],
        [  79.25      ],
        [  72.8       ],
        [  81.5       ],
        [  94.        ],
        [ 106.125     ],
        [ 120.33333333],
        [ 136.9       ],
        [ 127.        ],
        [ 184.        ],
        [ 217.        ],
        [ 155.        ],
        [ 130.75      ],
        [ 123.4       ],
        [ 137.        ],
        [  10.        ],
        [  40.5       ],
        [  60.33333333],
        [  77.5       ],
        [  93.6       ],
        [ 117.33333333],
        [ 140.42857143],
        [ 123.625     ],
        [ 117.        ],
        [ 118.1       ],
        [ 120.90909091],
        [ 127.5       ],
        [ 136.30769231],
        [ 146.78571429],
        [ 137.66666667],
        [   8.        ],
        [  37.5       ],
        [  50.66666667],
        [  68.25      ],
        [  89.8       ],
        [ 109.33333333],
        [ 128.57142857],
        [ 115.25      ],
        [ 106.        ],
        [ 104.6       ],
        [ 105.63636364],
        [ 111.16666667],
        [ 117.23076923],
        [ 125.71428571],
        [ 135.        ],
        [ 128.625     ],
        [ 186.        ],
        [  31.        ],
        [ 125.5       ],
        [ 164.        ],
        [ 191.75      ],
        [ 157.        ],
        [ 147.66666667],
        [ 158.        ],
        [  24.        ],
        [  42.        ],
        [  61.66666667],
        [  79.        ],
        [ 101.6       ],
        [ 121.66666667],
        [ 141.        ],
        [ 124.625     ],
        [ 115.88888889],
        [ 111.9       ],
        [ 113.54545455],
        [ 117.        ],
        [ 122.53846154],
        [ 131.78571429],
        [ 141.66666667],
        [ 134.3125    ],
        [  42.        ],
        [ 284.        ],
        [ 212.        ],
        [  29.        ],
        [  43.5       ],
        [  58.33333333],
        [  74.75      ],
        [  94.        ],
        [ 112.66666667],
        [ 177.        ],
        [ 192.        ],
        [ 204.33333333],
        [ 138.        ],
        [ 112.        ],
        [ 185.5       ],
        [   6.        ],
        [  36.        ],
        [  55.33333333],
        [  78.        ],
        [  96.8       ],
        [ 115.5       ],
        [ 132.85714286],
        [ 150.25      ],
        [ 140.77777778],
        [ 135.6       ],
        [ 134.72727273],
        [ 138.33333333],
        [ 143.84615385],
        [ 152.        ],
        [ 143.86666667],
        [  14.        ],
        [  33.5       ],
        [  57.        ],
        [  76.        ],
        [  98.4       ],
        [ 127.16666667],
        [ 112.57142857],
        [ 105.625     ],
        [ 104.66666667],
        [ 212.        ],
        [ 234.        ],
        [  34.        ],
        [  85.5       ],
        [ 113.        ],
        [ 136.        ],
        [ 156.8       ],
        [ 175.        ],
        [ 152.85714286],
        [ 142.5       ],
        [  68.        ],
        [ 180.5       ],
        [ 276.        ],
        [ 171.        ],
        [ 185.66666667],
        [ 202.75      ],
        [ 221.8       ],
        [ 191.33333333],
        [   1.        ],
        [  26.5       ],
        [  45.33333333],
        [  63.75      ],
        [  83.        ],
        [ 104.16666667],
        [ 125.85714286],
        [ 112.25      ],
        [ 103.44444444],
        [ 103.        ],
        [ 104.54545455],
        [ 109.83333333],
        [ 115.61538462],
        [ 123.57142857],
        [ 132.93333333],
        [ 125.625     ],
        [  18.        ],
        [  43.5       ],
        [  54.33333333],
        [  73.25      ],
        [  92.4       ],
        [ 112.5       ],
        [ 129.42857143],
        [ 114.25      ],
        [ 108.11111111],
        [ 104.4       ],
        [ 105.90909091],
        [ 110.08333333],
        [ 117.46153846],
        [ 125.85714286],
        [ 136.6       ],
        [ 129.75      ],
        [  22.        ],
        [  42.        ],
        [  57.66666667],
        [  74.5       ],
        [  98.8       ],
        [ 121.16666667],
        [ 140.        ],
        [ 125.375     ],
        [ 115.22222222],
        [ 112.7       ],
        [ 112.45454545],
        [ 115.66666667],
        [ 121.15384615],
        [ 130.14285714],
        [ 139.46666667],
        [ 131.3125    ],
        [  16.        ],
        [  31.        ],
        [  54.66666667],
        [  72.5       ],
        [  91.        ],
        [ 108.16666667],
        [ 130.42857143],
        [ 115.25      ],
        [ 108.33333333],
        [  99.6       ],
        [  51.        ],
        [  73.5       ],
        [  93.66666667],
        [ 110.75      ],
        [ 124.6       ],
        [ 144.33333333],
        [ 162.71428571],
        [   7.        ],
        [  37.5       ],
        [  53.        ],
        [  69.25      ],
        [  86.6       ],
        [ 104.66666667],
        [ 126.14285714],
        [ 111.25      ],
        [ 104.33333333],
        [ 101.6       ],
        [ 103.        ],
        [ 106.91666667],
        [ 113.61538462],
        [ 122.5       ],
        [ 132.13333333],
        [ 124.1875    ],
        [  19.        ],
        [  32.        ],
        [  57.        ],
        [  75.75      ],
        [  92.8       ],
        [ 112.66666667],
        [ 136.14285714],
        [ 121.125     ],
        [ 111.66666667],
        [ 109.2       ],
        [ 110.54545455],
        [ 115.5       ],
        [ 120.76923077],
        [ 129.71428571],
        [ 139.13333333],
        [ 131.5       ],
        [   2.        ],
        [  21.        ],
        [  41.        ],
        [  61.25      ],
        [  84.6       ],
        [ 102.16666667],
        [ 119.71428571],
        [ 138.875     ],
        [ 125.55555556],
        [ 120.2       ],
        [ 119.09090909],
        [ 121.91666667],
        [ 127.        ],
        [ 137.57142857],
        [ 129.26666667],
        [  28.        ],
        [  44.5       ],
        [  60.33333333],
        [  81.25      ],
        [  99.        ],
        [ 114.66666667],
        [ 133.42857143],
        [ 149.5       ],
        [ 133.44444444],
        [ 124.6       ],
        [ 123.54545455],
        [ 125.41666667],
        [ 131.38461538],
        [ 137.78571429],
        [ 146.33333333],
        [ 137.4375    ],
        [ 181.        ],
        [  17.        ],
        [  35.5       ],
        [  52.33333333],
        [  69.25      ],
        [  91.2       ],
        [ 111.16666667],
        [ 127.71428571],
        [ 114.75      ],
        [ 106.44444444],
        [ 104.9       ],
        [ 107.09090909],
        [ 110.83333333],
        [ 117.61538462],
        [ 126.71428571],
        [ 137.        ],
        [ 129.5625    ],
        [ 100.        ],
        [ 117.5       ],
        [ 136.66666667],
        [ 156.        ],
        [ 174.6       ],
        [ 194.        ],
        [ 282.        ],
        [ 192.        ],
        [ 175.66666667],
        [ 186.5       ],
        [  32.        ],
        [  40.        ],
        [  61.        ],
        [  77.75      ],
        [  96.8       ],
        [ 114.16666667],
        [ 138.        ],
        [ 122.375     ],
        [ 115.66666667],
        [ 113.4       ],
        [ 113.90909091],
        [ 118.16666667],
        [ 124.30769231],
        [ 131.71428571],
        [ 140.86666667],
        [ 133.875     ],
        [  23.        ],
        [  33.        ],
        [  57.33333333],
        [  78.25      ],
        [  95.8       ],
        [ 111.66666667],
        [ 129.85714286],
        [ 147.875     ],
        [ 135.66666667],
        [ 130.9       ],
        [ 130.09090909],
        [ 132.83333333],
        [ 137.69230769],
        [ 143.78571429],
        [ 152.8       ],
        [ 144.5       ],
        [  93.        ],
        [ 113.        ],
        [ 167.        ],
        [ 180.66666667],
        [  25.        ],
        [  36.        ],
        [  54.        ],
        [  72.33333333],
        [  90.5       ],
        [ 108.4       ],
        [ 126.66666667],
        [ 144.14285714],
        [ 161.5       ],
        [ 150.55555556],
        [ 145.9       ],
        [ 155.63636364],
        [ 145.83333333],
        [  13.        ],
        [  36.        ],
        [  54.        ],
        [  69.        ],
        [  87.        ],
        [ 105.33333333],
        [ 123.14285714],
        [ 139.5       ],
        [ 128.77777778],
        [ 123.3       ],
        [ 121.81818182],
        [ 125.58333333],
        [ 129.84615385],
        [ 136.71428571],
        [ 145.86666667],
        [ 137.25      ],
        [   3.        ],
        [  33.        ],
        [  57.        ],
        [  78.25      ],
        [ 103.        ],
        [ 124.83333333],
        [ 144.14285714],
        [ 127.5       ],
        [ 118.66666667],
        [ 115.1       ],
        [ 114.54545455],
        [ 117.25      ],
        [ 123.38461538],
        [ 131.        ],
        [ 139.73333333],
        [ 132.1875    ],
        [  34.        ],
        [  33.        ],
        [  90.        ],
        [ 121.        ],
        [  98.        ]]),
 array([  34.5       ,   55.33333333,   70.75      ,   87.6       ,
         104.5       ,  121.57142857,  139.875     ,  124.55555556,
         120.3       ,  120.90909091,  124.08333333,  129.38461538,
         136.21428571,  144.53333333,  135.625     ,   12.        ,
          33.5       ,   54.33333333,   75.75      ,   91.        ,
         112.        ,  130.57142857,  146.5       ,  136.22222222,
         132.9       ,  133.72727273,  137.33333333,  143.38461538,
         151.5       ,  161.33333333,  153.5625    ,   26.        ,
          37.5       ,   52.33333333,   77.5       ,  104.8       ,
         125.5       ,  144.85714286,  127.125     ,  117.55555556,
         114.4       ,  115.18181818,  117.66666667,  124.30769231,
         132.07142857,  141.66666667,  133.6875    ,   30.        ,
          37.        ,   51.        ,   69.        ,   88.6       ,
         106.83333333,  126.57142857,  112.25      ,  103.66666667,
         100.8       ,  101.81818182,  106.66666667,  113.92307692,
         122.71428571,  133.73333333,  127.        ,   15.        ,
          33.        ,   47.        ,   76.25      ,  101.        ,
         123.83333333,  143.14285714,  127.875     ,  119.44444444,
         125.7       ,  135.27272727,  147.66666667,  137.15384615,
           9.        ,   39.5       ,   58.        ,   77.        ,
          99.        ,  123.        ,  143.        ,  127.        ,
         119.        ,  117.6       ,  182.        ,  198.5       ,
         228.        ,  194.75      ,  183.        ,  178.16666667,
         182.57142857,  190.75      ,  202.        ,  185.        ,
          39.        ,   43.        ,   61.66666667,   80.25      ,
          96.8       ,  114.5       ,  130.71428571,  149.375     ,
         135.66666667,  130.6       ,  130.63636364,  132.91666667,
         138.23076923,  145.5       ,  155.13333333,  294.        ,
         158.        ,  150.        ,  218.        ,  232.        ,
         249.        ,  207.4       ,   38.        ,   34.5       ,
          60.        ,   72.        ,   21.        ,   31.5       ,
          53.66666667,   69.        ,   90.2       ,  113.83333333,
         136.14285714,  119.625     ,  111.88888889,  108.7       ,
         108.45454545,  111.41666667,  116.61538462,  124.85714286,
         134.4       ,  127.4375    ,   11.        ,   33.5       ,
          51.33333333,   73.25      ,   99.4       ,  120.5       ,
         141.42857143,  123.875     ,  114.44444444,  111.1       ,
         113.09090909,  116.        ,  121.84615385,  130.57142857,
         141.53333333,   74.        ,  160.5       ,  125.66666667,
         112.5       ,  113.6       ,  122.        ,  134.71428571,
         148.        ,  162.33333333,  147.6       ,  137.        ,
         151.5       ,   37.        ,   55.        ,   73.66666667,
          92.5       ,  111.        ,  134.33333333,  155.85714286,
         140.125     ,  132.22222222,  128.8       ,  129.90909091,
         133.75      ,  140.15384615,  148.35714286,  158.26666667,
         150.875     ,   27.        ,   42.        ,   54.        ,
          76.25      ,   93.4       ,  111.        ,  130.57142857,
         147.875     ,  134.55555556,  125.3       ,  125.90909091,
         129.66666667,  136.07692308,  143.42857143,  152.4       ,
         143.25      ,   35.        ,   85.        ,  114.66666667,
         140.        ,  162.4       ,  142.66666667,  133.57142857,
         131.125     ,  134.44444444,  139.6       ,  147.27272727,
         157.66666667,  146.07692308,  139.        ,  178.5       ,
         214.        ,  251.        ,  110.        ,   73.        ,
         108.        ,   71.5       ,    5.        ,   27.5       ,
          46.66666667,   64.        ,   82.        ,  105.5       ,
         128.28571429,  114.        ,  105.44444444,  102.7       ,
         103.81818182,  109.66666667,  116.23076923,  123.78571429,
         133.06666667,  124.8125    ,   20.        ,   30.5       ,
          50.66666667,   69.75      ,   87.2       ,  107.33333333,
         125.57142857,  144.625     ,  131.55555556,  124.5       ,
         123.27272727,  126.08333333,  130.46153846,  139.        ,
         148.53333333,  139.4375    ,  151.        ,  185.        ,